name: format
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  lint-linux:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: fmt
         run: bash format-check.sh
