name: lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint-linux:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: format
         run: bash format-check.sh
       - name: style
         run: bash style-check.sh